# -*- coding: utf-8 -*-
"""Hybrid Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bb--FKXNh6yJqEk0Q7_niUsbV13O6TET
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, StackingClassifier
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline   # <-- imblearn pipeline (handles samplers)

from sklearn.ensemble import VotingClassifier
ensemble = VotingClassifier(
    estimators=[('lr', log_reg), ('rf', rf_clf)],
    voting='soft'
)