# -*- coding: utf-8 -*-
"""RandomForest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yEOgoZ4_NOUyWZEm8hB6TeGDrd62PQ8S
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, StackingClassifier
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline   # <-- imblearn pipeline (handles samplers)



from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier(
    n_estimators=50,        # biggest impact on speed
    max_depth=20,            # prevents overly deep trees
    min_samples_split=10,    # fewer splits → faster
    min_samples_leaf=5,
    n_jobs=-1,               # use all CPU cores
    random_state=42
)
rf_clf.fit(X_train_resampled, y_train_resampled)